#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# if commitlint failed, launch git cz
#  echo red message

npx --no-install commitlint --edit  || (echo '\033[1;31m Your commit message is malformated, launching commitizen...\033[0m' && git cz)
